model:
  _target_: geobench_exp.torch_toolbox.prithvi_model.GeoBenchPrithviSegmentation
  prithvi_variant: "prithvi_eo_v2_tiny_tl"
  pretrained: true
  freeze_backbone: false
  decoder_type: "UperNetDecoder"
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 6e-5
    weight_decay: 0.05

datamodule:
  batch_size: 8
  band_names: "all"
